### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by cossssmin** [sheerlox/import-from-esm#128]
Hi there, thanks for the package, I'm using it in [Maizzle 5](https://github.com/maizzle/framework/tree/next).

Writing in because I can't pinpoint anything else that might be causing this. Could there be any dependency in `import-from-esm` that had a patch release and is breaking things?

```
$ npm ls import-from-esm
m5test@ C:\Users\Cosmin\Desktop\m5test
└─┬ @maizzle/framework@5.0.0-beta.20
  └─┬ @maizzle/cli@2.0.0-beta.2
    └── import-from-esm@1.3.4

$ node -v
v20.10.0
```

So the way I'm using it in `@maizzle/cli` is this:

```js
import importFrom from 'import-from-esm'

let { serve } = await importFrom(process.cwd(), '@maizzle/framework')
```

`@maizzle/framework` [package.json](https://github.com/maizzle/framework/blob/next/package.json) `exports` is this:

```json
"type": "module",
"exports": {
  ".": {
    "import": "./src/index.js",
    "types": "./types/index.d.ts"
  }
},
```

`serve` is a function exported by `src/index.js`.

Just yesterday I got a report from someone saying it errors out, and indeed it now does, this is the stack:

```
file:///C:/Users/Cosmin/Desktop/m5test/node_modules/import-from-esm/index.js:114
                const error = new Error(errorString);
                              ^

Error: Cannot find module '@maizzle/framework'
    at importFrom (file:///C:/Users/Cosmin/Desktop/m5test/node_modules/import-from-esm/index.js:114:17)
    at async Command.<anonymous> (file:///C:/Users/Cosmin/Desktop/m5test/node_modules/@maizzle/cli/src/index.js:94:25)
    at async Command.parseAsync (C:\Users\Cosmin\Desktop\m5test\node_modules\commander\lib\command.js:1092:5) {
  code: 'MODULE_NOT_FOUND'
}
```

Line 94 from `@maizzle/cli/src/index.js` is this:

```js
let { serve } = await importFrom(process.cwd(), '@maizzle/framework')
```

Any ideas what might be causing it and what could be done about it?

Thanks!

**Comment by cossssmin** [comment]
Sorry about this, managed to track it down to `cheerio` changing their import paths:

https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0

Closing 😇
